replicaCount: 1

image:
  repository: "wallabag/wallabag"
  pullPolicy: IfNotPresent
  tag: "2.6.13"

redis:
  repository: redis
  tag: alpine
  port: 6379

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  annotationsHttp:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-https-redirect@kubernetescrd    
  hosts:
    - host: wallabag.lukcic.pl
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: "2000m"
    memory: "2Gi"
  requests:
    cpu: "1000m"
    memory: "1Gi"

config:
  SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
  SYMFONY__ENV__DATABASE_HOST: "192.168.1.1"
  SYMFONY__ENV__DATABASE_PORT: "5432"
  SYMFONY__ENV__DATABASE_NAME: wallabag
  SYMFONY__ENV__MAILER_DSN: smtp://127.0.0.1
  SYMFONY__ENV__FROM_EMAIL: wallabag@example.com
  SYMFONY__ENV__DOMAIN_NAME: https://wallabag.example.com
  SYMFONY__ENV__SERVER_NAME: Wallabag"
  SYMFONY__ENV__REDIS_HOST: wallabag-redis
  SYMFONY__ENV__DATABASE_TABLE_PREFIX: "wallabag_"
  POPULATE_DATABASE: "false"

secrets:
  SYMFONY__ENV__DATABASE_USER: "d2FsbGFiYWc="
  SYMFONY__ENV__DATABASE_PASSWORD: "d2FsbGFiYWc="