---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
  SYMFONY__ENV__DATABASE_HOST: "192.168.254.70"
  SYMFONY__ENV__DATABASE_PORT: "5432"
  SYMFONY__ENV__DATABASE_NAME: wallabag_test
  SYMFONY__ENV__MAILER_DSN: smtp://127.0.0.1
  SYMFONY__ENV__FROM_EMAIL: wallabag@example.com
  SYMFONY__ENV__DOMAIN_NAME: https://wallabag.lukcic.pl
  SYMFONY__ENV__SERVER_NAME: "lukcic's wallabag"
  SYMFONY__ENV__REDIS_HOST: wallabag-redis
  SYMFONY__ENV__DATABASE_TABLE_PREFIX: "wallabag_"
  POPULATE_DATABASE: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wallabag-ingress-https
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  rules:
    - host: wallabag.lukcic.pl
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: wallabag
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wallabag-ingress-http
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-https-redirect@kubernetescrd
spec:
  rules:
    - host: wallabag.lukcic.pl
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: 80
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: wallabag
# spec:
#   secretName: wallabag-lukcic-pl-ssl-cert
#   issuerRef:
#     name: cloudflare-cluster-issuer
#     kind: ClusterIssuer
#   dnsNames:
#     - wallabag.lukcic.pl

