apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: wallabag/wallabag:2.6.13
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: wallabag-config
            - secretRef:
                name: wallabag-secrets
          volumeMounts:
            - name: wallabag-img
              mountPath: /var/www/wallabag/web/assets/images
          resources:
            limits:
              cpu: "2000m"
              memory: "2Gi"
            requests:
              cpu: "1000m"
              memory: "1Gi"
      volumes:
        - name: wallabag-img
          persistentVolumeClaim:
            claimName: wallabag-img