apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-img
  labels:
    type: LocalVolume
spec:
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /{{ .Chart.Name }}-img
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-img
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi