apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-redis
spec:
  selector:
    app: {{ .Chart.Name }}-redis
  ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.repository }}:{{ .Values.redis.tag | default "redis:alpine" }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
