---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
{{- with .Values.secrets }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}
spec:
  secretName: {{ .Chart.Name }}--ssl-cert
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - {{ (first .Values.ingress.hosts).host }}