apiVersion: v1
kind: PersistentVolume
metadata:
  name: wallabag-img
  labels:
    type: LocalVolume
spec:
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /wallabag-img
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-img
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      containers:
        - name: wallabag
          image: wallabag/wallabag:2.6.13
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: wallabag-config
            - secretRef:
                name: wallabag-secrets
          volumeMounts:
            - name: wallabag-img
              mountPath: /var/www/wallabag/web/assets/images
          resources:
            limits:
              cpu: "2000m"
              memory: "2Gi"
            requests:
              cpu: "1000m"
              memory: "1Gi"
      volumes:
        - name: wallabag-img
          persistentVolumeClaim:
            claimName: wallabag-img